<?php
header('Content-Type: application/json');

// Türkiye'deki tüm iller ve ilçeleri
$data = [
    'iller' => [
        'ADANA' => [
            'SEYHAN',
            'YÜREĞİR',
            'ÇUKUROVA',
            'Kozan',
            'Ceyhan',
            'Feke',
            'Sarıçam',
            'Aladağ',
            'Tufanbeyli',
            'Pozantı',
            'İmamoğlu',
            'Karaisalı',
            'Akdeniz',
        ],
        'ADIYAMAN' => [
            'MERKEZ',
            'KAHTA',
            'GÖLBAŞI',
            'ÇELİKHAN',
            'SAMSAT',
            'Besni',
            'Pınarbaşı',
            'Yenipınar',
        ],
        'AFYONKARAHİSAR' => [
            'MERKEZ',
            'SANDIKLI',
            'DİNAR',
            'ÇAY',
            'İHSANİYE',
            'Bolvadin',
            'Emirdağ',
            'Afyon',
            'Şuhut',
        ],
        'AĞRI' => [
            'MERKEZ',
            'DOĞUBAYAZIT',
            'PATNOS',
            'TUTAK',
            'Diyadin',
            'Hamur',
            'Eleşkirt',
        ],
        'AKSARAY' => [
            'MERKEZ',
            'GÜZELYURT',
            'KADINHAN',
            'Sarıyahşi',
            'Ağaçören',
            'Ortaköy',
            'Kızılkaya',
        ],
        'AMASYA' => [
            'MERKEZ',
            'GÖYNÜCEK',
            'HAVAİ',
            'SULUOVA',
            'Taşova',
            'Merzifon',
            'Amasya',
        ],
        'ANKARA' => [
            'ÇANKAYA',
            'KEÇİÖREN',
            'MAMAK',
            'SİNCAN',
            'POLATLI',
            'Gölbaşı',
            'Etimesgut',
            'Yenimahalle',
            'Akyurt',
            'Bala',
            'Çubuk',
            'Kahramankazan',
            'Nallıhan',
            'Pursaklar',
            'Şereflikoçhisar',
            'Kızılcahamam',
            'Güdül',
            'Haymana',
        ],
        'ANTALYA' => [
            'MURATPAŞA',
            'KEPEZ',
            'ALANYA',
            'KEMER',
            'MANAVGAT',
            'DÖŞEMEALTI',
            'KONYAALTI',
            'SERİK',
            'FINIKE',
            'KALKAN',
            'ELMALI',
            'GÖNEN',
            'KAS',
            'DEMRE',
            'GÜNDOĞMUŞ',
            'AKSU',
            'İBRADI',
            'DÖŞEMEALTI',
        ],
        'ARTVİN' => [
            'MERKEZ',
            'HOPA',
            'BORÇKA',
            'ARDANUÇ',
            'YUSUFELİ',
            'Murgul',
            'Şavşat',
        ],
        'AYDIN' => [
            'MERKEZ',
            'KUSADASI',
            'DİDİM',
            'EFELER',
            'SÖKE',
            'BOZDOĞAN',
            'ÇİNE',
            'Germencik',
            'Karacasu',
            'Nazilli',
            'Kuyucak',
            'Buharkent',
            'İncirliova',
        ],
        'BALIKESİR' => [
            'MERKEZ',
            'ALTIEYLÜL',
            'KARESİ',
            'EDREMİT',
            'SUSURLUK',
            'BURHANİYE',
            'GÖNEN',
            'DURSUNBEY',
            'MARMARA',
            'Sındırgı',
            'Bigadiç',
            'Kepsut',
            'Manyas',
            'Balya',
            'Havran',
        ],
        'BARTIN' => [
            'MERKEZ',
            'Kozcağız',
            'Ulus',
            'Amasra',
            'Kurucaşile',
        ],
        'BATMAN' => [
            'MERKEZ',
            'BEŞİRİ',
            'Gercüş',
            'Kozluk',
            'Sason',
            'Hasankeyf',
        ],
        'BAYBURT' => [
            'MERKEZ',
            'DEMİRÖZÜ',
            'Köyceğiz',
        ],
        'BİLECİK' => [
            'MERKEZ',
            'BOZÜYÜK',
            'Pazaryeri',
            'Söğüt',
            'Bilecik',
        ],
        'BİNGÖL' => [
            'MERKEZ',
            'KİĞI',
            'GENÇ',
            'YAYLADAĞI',
            'Solhan',
            'Adaklı',
            'Bingöl',
        ],
        'BİTLİS' => [
            'MERKEZ',
            'ADILCEVAZ',
            'Hizan',
            'Tatvan',
            'Güroymak',
            'Ahlat',
            'Bitlis',
        ],
        'BOLU' => [
            'MERKEZ',
            'GEREDİ',
            'Dörtdivan',
            'Kıbrıscık',
            'Mudurnu',
            'Seben',
            'Bolu',
        ],
        'BURDUR' => [
            'MERKEZ',
            'GÖLHİSAR',
            'Tefenni',
            'Karamanlı',
            'Çavdır',
            'Ağlasun',
            'Bucak',
            'Altınyayla',
            'Yeşilova',
        ],
        'ÇANAKKALE' => [
            'MERKEZ',
            'BAYRAMİÇ',
            'Biga',
            'Çan',
            'Eceabat',
            'Gelibolu',
            'Lapseki',
            'Troy',
            'Yenice',
        ],
        'ÇANKIRI' => [
            'MERKEZ',
            'ÇERKEŞ',
            'Kızılırmak',
            'Kurşunlu',
            'Orta',
            'Şabanözü',
            'Çankırı',
        ],
        'ÇORUM' => [
            'MERKEZ',
            'ALACA',
            'BAYAT',
            'Boğazkale',
            'Çorum',
            'İskilip',
            'Osmancık',
            'Sungurlu',
            'Uğurludağ',
        ],
        'DENİZLİ' => [
            'MERKEZ',
            'BULDAAN',
            'ÇAL',
            'Çivril',
            'Güney',
            'Pamukkale',
            'Serinhisar',
            'Tavas',
            'Acıpayam',
        ],
        'DİYARBAKIR' => [
            'MERKEZ',
            'BAĞLAR',
            'KAYAPINAR',
            'SUR',
            'Çınar',
            'Dicle',
            'Ergani',
            'Hani',
            'Kocaköy',
            'Lice',
            'Silvan',
            'Bismil',
            'Diyarbakır',
        ],
        'EDİRNE' => [
            'MERKEZ',
            'Enez',
            'Havsa',
            'İpsala',
            'Keşan',
            'Lalapaşa',
            'Uzunköprü',
        ],
        'ELAZIĞ' => [
            'MERKEZ',
            'Ağın',
            'Baskil',
            'Karakoçan',
            'Kovancılar',
            'Maden',
            'Palu',
            'Sivrice',
            'Elazığ',
        ],
        'ERZİNCAN' => [
            'MERKEZ',
            'Çayırlı',
            'İliç',
            'Kemaliye',
            'Otlukbeli',
            'Refahiye',
            'Tercan',
            'Erzincan',
        ],
        'ERZURUM' => [
            'MERKEZ',
            'AZİZİYE',
            'Hınıs',
            'Horasan',
            'Oltu',
            'Pasinler',
            'Pazaryolu',
            'Tekman',
            'Tortum',
            'Erzurum',
        ],
        'ESKİŞEHİR' => [
            'MERKEZ',
            'ALPU',
            'Beylikova',
            'Çifteler',
            'Günyüzü',
            'Han',
            'İnönü',
            'Odunpazarı',
            'Tepebaşı',
            'Seyitgazi',
        ],
        'GAZİANTEP' => [
            'MERKEZ',
            'ŞAHİNBEY',
            'OLUCAK',
            'Nizip',
            'Oğuzeli',
            'Araban',
            'Yavuzeli',
            'Karkamış',
            'Nizip',
            'Gaziantep',
        ],
        'GİRESUN' => [
            'MERKEZ',
            'ALUCRA',
            'Çamoluk',
            'Dereli',
            'Doğankent',
            'Espiye',
            'Eynesil',
            'Giresun',
            'Görele',
            'Keşap',
            'Piraziz',
            'Şebinkarahisar',
            'Tirebolu',
        ],
        'GÜMÜŞHANE' => [
            'MERKEZ',
            'KELKİT',
            'TORUL',
            'Şiran',
            'Gümüşhane',
        ],
        'HATAY' => [
            'MERKEZ',
            'ANTAKYA',
            'DEFNE',
            'Dörtyol',
            'Erzin',
            'Hassa',
            'İskenderun',
            'Kaman',
            'Payas',
            'Reyhanlı',
            'Samandağ',
            'Altınözü',
            'Erzin',
            'Dörtyol',
        ],
        'IĞDIR' => [
            'MERKEZ',
            'ARALIK',
            'Karakoyunlu',
            'Tuzluca',
        ],
        'ISPARTA' => [
            'MERKEZ',
            'GÖNEN',
            'Isparta',
            'Şarkikaraağaç',
            'Yalvaç',
            'Sütçüler',
            'Uluborlu',
            'Eğirdir',
            'Keçiborlu',
        ],
        'İSTANBUL' => [
            'BEYOĞLU',
            'KADIKÖY',
            'ÜSKÜDAR',
            'BAKIRKÖY',
            'ŞİŞLİ',
            'BAĞCILAR',
            'KÜÇÜKÇEKMECE',
            'AVCILAR',
            'BÜYÜKÇEKMECE',
            'SULTANBEYLİ',
            'ÇEKMEKÖY',
            'PENDİK',
            'KARTAL',
            'MALTEPE',
            'ATAŞEHİR',
            'SARIEKMEK',
            'SİLİVRİ',
        ],
        'İZMİR' => [
            'BORNOVA',
            'KARŞIYAKA',
            'BAYRAKLI',
            'GÜZELBAĞ',
            'MENEMEN',
            'ALİAĞA',
            'DİKİLİ',
            'FOÇA',
            'KEMALPAŞA',
            'ÖDEMİŞ',
            'SELÇUK',
            'TİRE',
            'URLA',
            'ÇEŞME',
            'KONAK',
            'BAYINDIR',
            'BERGAMA',
            'GÜZELBAHÇE',
            'NARLIDERE',
            'SEFERİHİSAR',
        ],
        'KASTAMONU' => [
            'MERKEZ',
            'ABANA',
            'AĞLI',
            'Çatalzeytin',
            'Daday',
            'Devrekani',
            'Hanönü',
            'İnebolu',
            'Kastamonu',
            'Küre',
            'Pınarbaşı',
            'Seydiler',
            'Tosya',
        ],
        'KAYSERİ' => [
            'MERKEZ',
            'BÜNYAN',
            'DEVELİ',
            'Hacılar',
            'İncesu',
            'Talas',
            'Felik',
            'Pınarbaşı',
            'Kayseri',
        ],
        'KIRKLARELİ' => [
            'MERKEZ',
            'BABAESKİ',
            'DEMİRKÖY',
            'Kofçaz',
            'Lüleburgaz',
            'Pınarhisar',
            'Vize',
        ],
        'KIRŞEHİR' => [
            'MERKEZ',
            'AKÇAKENT',
            'Kaman',
            'Mucur',
            'Çiçekdağı',
            'Boztepe',
        ],
        'KONYA' => [
            'MERKEZ',
            'KARATAY',
            'SELÇUKLU',
            'MERAM',
            'Ereğli',
            'Akşehir',
            'Seydişehir',
            'Çumra',
            'Ilgın',
            'Kulu',
            'Tuzlukçu',
            'Hüyük',
            'Bozkır',
            'Derebucak',
            'Beyşehir',
            'Aksaray',
            'Cihanbeyli',
            'Kulu',
            'Seydişehir',
        ],
        'KÜTAHYA' => [
            'MERKEZ',
            'ALTINTAŞ',
            'Dumlupınar',
            'Gediz',
            'Hisarcık',
            'Pazarlar',
            'Simav',
            'Tavşanlı',
            'Kütahya',
        ],
        'MALATYA' => [
            'MERKEZ',
            'AKÇADAĞ',
            'BATTALGAZİ',
            'Hekimhan',
            'Kale',
            'Pütürge',
            'Yeşilyurt',
            'Darende',
            'Doğanşehir',
            'Malatya',
        ],
        'MANİSA' => [
            'MERKEZ',
            'AHMETLİ',
            'GÖLMARMARA',
            'KULA',
            'SALİHLİ',
            'SOMA',
            'TURGUTLU',
            'ŞEHİRLİ',
            'Demirtaş',
        ],
        'MARDİN' => [
            'MERKEZ',
            'ARTUKLU',
            'DARGEÇİT',
            'Kızıltepe',
            'Nusaybin',
            'Savur',
            'Dargeçit',
            'Mazıdağı',
            'Midyat',
            'Derik',
        ],
        'MUĞLA' => [
            'MERKEZ',
            'BODRUM',
            'DALAMAN',
            'FETHİYE',
            'MARMARİS',
            'Menteşe',
            'Köyceğiz',
            'Dalaman',
            'Ortaca',
            'Ula',
        ],
        'NEVŞEHİR' => [
            'MERKEZ',
            'AVANOS',
            'GÜVERCİNLIK',
            'Hacıbektaş',
            'Ürgüp',
        ],
        'NİĞDE' => [
            'MERKEZ',
            'BOR',
            'Çamardı',
            'Ulukışla',
            'Niğde',
        ],
        'ORDU' => [
            'MERKEZ',
            'ALTINORDU',
            'ÜNYE',
            'GİRESUN',
            'Fatsa',
            'Korgan',
            'Perşembe',
            'Gölköy',
            'Kumru',
            'Çaybaşı',
        ],
        'RİZE' => [
            'MERKEZ',
            'ÇAYELİ',
            'FINDIKLI',
            'İkizdere',
            'Pazar',
            'Rize',
        ],
        'SAKARYA' => [
            'MERKEZ',
            'ADAPAZARI',
            'SERDİVAN',
            'Erenler',
            'Hendek',
            'Karasu',
            'Sapanca',
            'Karla',
            'Akyazı',
        ],
        'SAMSUN' => [
            'MERKEZ',
            'ATAKUM',
            'CANİK',
            'İLKADIM',
            'Bafra',
            'Ladik',
            'Salıpazarı',
            'Tekkeköy',
            'Vezirköprü',
        ],
        'SİİRT' => [
            'MERKEZ',
            'Eruh',
            'Kurtalan',
            'Pervari',
            'Siirt',
        ],
        'SİNOP' => [
            'MERKEZ',
            'BOYABAT',
            'Durağan',
            'Erfelek',
            'Gerze',
            'Sıvas',
            'Sinop',
        ],
        'SİVAS' => [
            'MERKEZ',
            'GEMEREK',
            'KANGAL',
            'Sivas',
            'Zara',
            'Divriği',
            'Ulaş',
            'Hafik',
            'Koyulhisar',
        ],
        'TEKİRDAĞ' => [
            'MERKEZ',
            'ÇERKEZKÖY',
            'MARMARAEREĞLİ',
            'Süleymanpaşa',
            'Kapaklı',
            'Ergene',
            'Hayrabolu',
            'Malkara',
        ],
        'TOKAT' => [
            'MERKEZ',
            'ARTOVA',
            'BİZİM',
            'Erbaa',
            'Niksar',
            'Reşadiye',
            'Tokat',
        ],
        'TRABZON' => [
            'MERKEZ',
            'AKÇAABAT',
            'SÜRMENE',
            'Çaykara',
            'Düzköy',
            'Of',
            'Tonya',
            'Vakfıkebir',
            'Yomra',
        ],
        'TUNCELİ' => [
            'MERKEZ',
            'ÇEMİŞGEZEK',
            'Hozat',
            'Nazımiye',
            'Ovacık',
            'Pertek',
            'Tunceli',
        ],
        'ŞANLIURFA' => [
            'MERKEZ',
            'HALİLİYE',
            'Eyyübiye',
            'Siverek',
            'Birecik',
            'Bozova',
            'Ceylanpınar',
            'Halfeti',
            'Suruç',
        ],
        'UŞAK' => [
            'MERKEZ',
            'BANAZ',
            'Eşme',
            'Sivaslı',
            'Ulubey',
            'Uşak',
        ],
        'VAN' => [
            'MERKEZ',
            'EDREMİT',
            'GÜRBULAK',
            'İPEKYOLU',
            'Özalp',
            'Tuşba',
            'Van',
        ],
        'YALOVA' => [
            'MERKEZ',
            'ÇINARCIK',
            'KARAMÜRSEL',
            'TERMAL',
            'Altınova',
            'Yalova',
        ],
        'ZONGULDAK' => [
            'MERKEZ',
            'EREĞLİ',
            'Kozlu',
            'Devrek',
            'Gökçebey',
            'Alaplı',
            'Zonguldak',
        ],
    ],
    'dosya_turleri' => [
        'SHKM Dosyaları',
        'LİHKAB',
        'Takım Proje',
    ],
    'islem_turleri' => [
        'İfraz Dosyası',
        'Tus Dosyası',
        'Röperli Kroki',
        'Bağımsız Bölüm Planı',
        'Sınırlandırma Haritası',
        'Zemin Tespit Tutanağı',
        'Yapı Denetim Fenni Mesul',
        'Kamulaştırma Haritası',
        'Çalışma Dosyası',
        'Diğer Dosyalar',
        '18. Madde Uygulaması',
        'Plankote',
        'Halihazır Harita',
        'Kat İrtifakı - Kat Mülkiyeti',
        'Yola Terk Dosyası',
        'Yoldan İhdas Dosyası',
        'Numarataj',
        'Yer Tespiti',
        'Yapı Aplikasyon Projesi',
        '1/25000 Harita',
        'Rıza-i Taksim',
        'Ölçü Krokisi',
        'Vaziyet Planı',
        '3BSYM Üç Boyut',
        'Mahkeme Dosyası',
    ],
];

echo json_encode($data); 